CC     = gcc
DEFS   =
CFLAGS =
COPTS  = -D_DOUBLE -g -std=c99
OMPFL  = -fopenmp

ifeq ($(DEBUG),1)
COPTS += -D_DEBUG
endif

ifeq ($(Wall),1)
COPTS += -Wall
endif

ifneq ($(MKL),0)
ifndef MKLROOT
MKLROOT     = /opt/intel/composer_xe_2013_sp1.2.144/mkl
endif
MKL_LIBS    = -lmkl_intel_lp64 -lmkl_intel_thread -lmkl_core -liomp5
MKL_LDIR    = $(MKLROOT)/lib/intel64 $(MKLROOT)/../compiler/lib/intel64
MKL.IDIR    = $(MKLROOT)/include
MKL.LIBS    = $(addprefix -L, $(MKL_LDIR)) -Wl,-Bstatic $(MKL_LIBS) -Wl,-Bdynamic
MKL.KERS    = mkl_spmv
COPTS      += -D_MKL_ENABLE

ifneq ($(MKL_NEW_SPMV),0)
ifndef MKLNSROOT
MKLNSROOT   = /opt/intel/composer_xe_2013_sp1.2.144/mkl
endif
MKLNS_LIBS  = -lmkl_spmv_pkg_avx
MKLNS_LDIR  = $(MKLNSROOT)/lib/intel64
MKLNS.IDIR  = $(MKLNSROOT)/include
MKLNS.LIBS  = $(addprefix -L, $(MKLNS_LDIR)) -Wl,-Bstatic $(MKLNS_LIBS) -Wl,-Bdynamic
MKLNS.KERS  = mkl_new_spmv
COPTS      += -D_MKL_NEW_SPMV_ENABLE
endif
endif

_DIR.ROOT   = $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
DIR.ROOT    = $(_DIR.ROOT:%/=%)
DIR.COMMON  = $(DIR.ROOT)/common
DIR.SPMV    = $(DIR.ROOT)/spmv
DIR.KERS    = $(DIR.SPMV)/kernels
DIR.BENCH   = $(DIR.ROOT)/bench
DIR.BUILD   = $(DIR.ROOT)/build
DIR.OUT     = $(DIR.BUILD)

# serv definitions
C.COMP      = $(CC) $(COPTS) $(DEFS) $(CFLAGS)
C.COMP.OMP  = $(C.COMP) $(OMPFL)
